package com.k1ngtle.vsia.phone.client;

import java.util.Set;

public final class PhoneSystemStringCatalog {
    private static final Set<String> STRINGS =
            Set.of(
            "  • No Service",
            "  • SMS",
            " Cellular",
            " conditions",
            " dBm",
            " in ",
            " is available.",
            " network(s) in range",
            " of ",
            " radio access.\n\n",
            " → HTTP → ",
            "% · Low Power",
            "%.0f cal",
            "%.0f m",
            "%.1f Mbps",
            "%.1f dB",
            "%.1f m",
            "%.2f credits",
            "%.3f GHz",
            "%010d",
            "%02d:%02d",
            "%02d:%02d.%02d",
            "%02d:%02d:%02d",
            "%08d",
            "%s %s | RSRP %d dBm | SINR %.1f dB",
            "%s %s | RSRP %d dBm | SINR %.1f dB | %.0f m",
            "%s (%d dBm)",
            "&amp;",
            "&gt;",
            "&lt;",
            "&nbsp;",
            "&quot;",
            "(?is)<!--.*?-->",
            "(?is)<[^>]+>|[^<]+",
            "(?is)<body([^>]*)>(.*)</body>",
            "(?is)<link\\b[^>]*>",
            "(?is)<script[^>]*>.*?</script>",
            "(?is)<style[^>]*>(.*?)</style>",
            "(?is)<style[^>]*>.*?</style>",
            "(?is)<title[^>]*>(.*?)</title>",
            "(?s)([^{}]+)\\{([^{}]*)}",
            "(?s)/\\*.*?\\*/",
            "([A-Za-z_:][-A-Za-z0-9_:.]*)\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s>]+))",
            "+ Add Event",
            "+ Add Reminder",
            "+ New Note",
            ".card{background:white;padding:10px;border:1px #d1d1d6;border-radius:10px;margin-bottom:10px;}",
            ".hero{background:#0a84ff;color:white;padding:12px;border-radius:12px;margin-bottom:10px;text-align:center;}",
            ".online{color:green;font-weight:bold;}",
            "0.0 Mbps",
            "02:%02X:%02X:%02X:%02X:%02X",
            "1G",
            "1x",
            "24-Hour Time",
            "2G",
            "2x",
            "3G",
            "5G",
            "802.11 AP",
            "802.11 authentication",
            "<!doctype html>",
            "</body>",
            "</head>",
            "</header>",
            "</html>",
            "</section>",
            "<a href=\"/\">Back Home</a>",
            "<a href=\"/about.html\">Open About Page</a>",
            "<body>",
            "<h1>About This Test</h1>",
            "<h1>VSIA Phone Web Test</h1>",
            "<h2>Cross-player test</h2>",
            "<h2>Server Rack</h2>",
            "<head>",
            "<header class=\"hero\">",
            "<html>",
            "<link rel=\"stylesheet\" href=\"/styles.css\">",
            "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
            "<p class=\"online\">ONLINE</p>",
            "<p>Give this domain to another player and let them open it from their phone.</p>",
            "<p>If you can read this on the Temporary iPhone, HTTP, virtual hosting, page transfer and HTML rendering are working.</p>",
            "<p>This is a second file from the same published W1.28 project.</p>",
            "<p>This page is served by the real W1.28 website backend.</p>",
            "<section class=\"card\">",
            "<title>About</title>",
            "<title>VSIA Phone Test</title>",
            "A",
            "ACTIVE",
            "AMPS",
            "AP Distance",
            "APP PRIVACY",
            "ASSOCIATING",
            "AUTHENTICATED",
            "AUTHENTICATING",
            "AUTOMATIC UPDATES",
            "About",
            "Access point disappeared during association",
            "Access point is no longer in range",
            "Accessibility",
            "Action Button",
            "Activate",
            "Activation Code",
            "Active Interface",
            "ActiveIccid",
            "Add Bookmark",
            "Add Current",
            "Add Event",
            "Add eSIM",
            "Address Copied",
            "Aero",
            "Air",
            "Airplane Mode",
            "Airplane Mode is on. Turn on Wi-Fi or turn off Airplane Mode to use network data.",
            "Airplane Mode · Wi-Fi available",
            "Alert Volume",
            "Allow Messages",
            "Allow Notifications",
            "ApSecurity",
            "ApSsid",
            "App Store",
            "Apple",
            "Apple Music",
            "Apps",
            "Armor",
            "Associating with ",
            "Audio Descriptions",
            "AuthSecret",
            "Authenticated",
            "Auto-Join",
            "Auto-joining ",
            "Automatic",
            "Automatically Download",
            "Automatically Install",
            "Available Balance",
            "BANNERS & HISTORY",
            "BRIGHTNESS",
            "BSSID",
            "Bad Request",
            "Band",
            "Battery",
            "Battery Health",
            "Battery Level",
            "Battery must be at least 20%",
            "Bing",
            "Bluetooth",
            "Bluetooth is Off",
            "Bluetooth stays available in Airplane Mode unless you turn it off.",
            "Body",
            "Bold Text",
            "Bookmark Added",
            "Bookmark Removed",
            "Bookmarks",
            "Brightness affects the whole simulated phone display.",
            "Browser",
            "Browser request blocked by authoritative subscriber/RF validation",
            "Browser request failed before HTTP response",
            "Browser → Cellular → UE → gNB → 5G Core → UPF → ",
            "Browser → Wi-Fi → 802.11 → AP → Router → ",
            "Building VS:IA",
            "Button Shapes",
            "CAMPED",
            "CELLULAR",
            "CH ›",
            "CONNECTED",
            "CONTACTS",
            "Calendar",
            "Camera",
            "Camera Off",
            "Camera On",
            "Camera Preview",
            "Camped on serving cell",
            "Cancel",
            "Captured",
            "Carrier",
            "Cell ",
            "Cell selection",
            "CellIdentity",
            "Cellular",
            "Cellular / Wi-Fi / Media services online",
            "Cellular Data",
            "Cellular Data Off",
            "Cellular Data is turned off. SMS remains available when cellular service is registered.",
            "Cellular Diagnostics",
            "Cellular data is off",
            "Cellular data is turned off",
            "Cellular packet data requires an authenticated subscriber profile. Install a physical SIM or activate an eSIM first.",
            "Cellular radio is turned off",
            "Cellular radio link is below service threshold: RSRP %d dBm, SINR %.1f dB",
            "Cellular radio link is too weak for packet data: RSRP %d dBm, SINR %.1f dB",
            "CellularRan",
            "Channel",
            "Check for Update",
            "Checking for Update...",
            "Choose Language",
            "Choose Region",
            "Clear",
            "Clear Completed",
            "Clears local settings, notification history, stopwatch state, and remembered Wi-Fi data. Server-side SMS and SIM data remain.",
            "Clears remembered Wi-Fi passwords and restores local radio preferences.",
            "Clock",
            "Close",
            "Compose",
            "Configure IP",
            "Configuring DNS",
            "Confirm",
            "Confirm Reset",
            "Connected",
            "Controls the Search pill shown above the dock.",
            "Controls whether VS:IA Web can send requests over the simulated local network.",
            "Copy Link",
            "Copy website address",
            "Core",
            "Current",
            "Current Position",
            "Current Tab",
            "DELIVERED",
            "DEREGISTERED",
            "DEV code: ",
            "DEV: Provision Test SIM",
            "DEV: enter your own number for loopback testing",
            "DHCP",
            "DNS",
            "DNS A: ",
            "DO NOT DISTURB",
            "Data Off",
            "DataEnabled",
            "Date",
            "Date & Time",
            "Day ",
            "Delete",
            "Desktop Minecraft cannot drive a phone vibration motor, so haptics are represented by a short UI pulse.",
            "Developer Log",
            "Devices",
            "Diagnostics",
            "Diagnostics >",
            "Differentiate Without Color",
            "Digital Horizon",
            "Direct Rack",
            "Direct Server Rack browsing needs a website host.\n",
            "Direct rack URL: ",
            "Disconnected",
            "Display",
            "Display & Brightness",
            "Display & Text Size",
            "Distance",
            "Do Not Disturb",
            "Do Not Disturb silences Messages banners and alert sounds unless Messages is allowed. Messages still arrive.",
            "Domain: ",
            "Done",
            "Download Update",
            "Download through SM-DP+ over Wi-Fi",
            "Downloading PhoneOS ",
            "Downloading PhoneOS %s",
            "Dusk",
            "EID ",
            "EPC",
            "ESIM",
            "EXCELLENT",
            "Edit Event",
            "Edit Note",
            "Eid",
            "EidBinding",
            "Emergency SOS",
            "Enable",
            "Enabled",
            "End",
            "End Workout",
            "Engineering episodes",
            "English (UK)",
            "Enter Activation Code",
            "Enter Password",
            "Enter a VS:IA website hostname such as example.com.",
            "Erase All Content and Settings",
            "Erase Local Phone Data",
            "Erase This VS:IA Phone?",
            "EsimIccid",
            "Est. Downlink",
            "Estimated DL",
            "Event Title",
            "Experience Level",
            "FAILED",
            "FAIR",
            "FEATURED",
            "Face ID & Attention",
            "Face ID & Passcode",
            "FaceTime",
            "Favorites",
            "Find My",
            "First Day of Week",
            "Fitness",
            "Focus",
            "Focus can silence banners without blocking message delivery.",
            "Food",
            "Forget This Network",
            "Forgot network",
            "Frequently Visited",
            "From",
            "From ",
            "From %s",
            "From Admin",
            "From Player",
            "Front",
            "G",
            "GATEWAY",
            "GET",
            "GOOD",
            "GSM",
            "General",
            "Google",
            "Graphite",
            "H:13°  L:10°",
            "Haptics",
            "Health",
            "Health data unavailable",
            "HmacSHA256",
            "Home",
            "Home Screen",
            "Home Screen & App Library",
            "Hover Text",
            "ICCID: ",
            "IDLE",
            "INACTIVE",
            "IP Address",
            "IPV4 ADDRESS",
            "ISP1 DNS",
            "ISP1 DNS has no A record for ",
            "Iccid",
            "Id",
            "Image",
            "Image file missing",
            "Image unavailable",
            "Imsi",
            "Inbox",
            "Inbox is Empty",
            "Incorrect Wi-Fi password",
            "Increase Contrast",
            "Insert from inventory",
            "Install Now",
            "Installing update...",
            "Internet connection required",
            "Invalid IPv4 address: ",
            "Invalid address.",
            "Invalid website address.",
            "Invalid website hostname.",
            "Join",
            "Keep this page open",
            "LIVE",
            "LOCAL",
            "LPA:1$vsia.smdp$DEV",
            "LTE",
            "Lab",
            "Language & Region",
            "Large Purchase",
            "Larger Text",
            "LastAuthStatus",
            "Learn more...",
            "Live top-down terrain samples around your current player position.",
            "Live world conditions from the current Minecraft session.",
            "Live world coordinates",
            "Loading Website",
            "Local Network",
            "Local Network access is disabled.",
            "Lock Screen",
            "Low Power Mode",
            "Low Power Mode reduces background wireless refresh frequency.",
            "MINECRAFT-VSIA",
            "MY DEVICES",
            "Mail",
            "Map unavailable",
            "Maps",
            "Maximum Tabs Reached",
            "Measurement System",
            "Message",
            "Messages",
            "Messages Notifications",
            "Messages are still delivered when notifications are off.",
            "Mic Live",
            "Model Name",
            "Model Number",
            "Mon",
            "Motion",
            "Move",
            "Move closer to an access point",
            "Msisdn",
            "Music",
            "Mute",
            "Muted",
            "NAS",
            "NAS State",
            "NETWORK",
            "NETWORKS",
            "NO SERVICE",
            "NO SIGNAL",
            "NOT AUTHENTICATED",
            "Name",
            "Network",
            "Network Lab",
            "Network Ops",
            "Network Setup",
            "Network Status",
            "New",
            "New Message",
            "New Note",
            "News",
            "NextSubscriberNumber",
            "Night Operations",
            "No Bluetooth devices registered",
            "No Bookmarks Yet",
            "No Connection",
            "No Events",
            "No Media Playing",
            "No Messages",
            "No Notes",
            "No Photos",
            "No Reminders",
            "No SIM",
            "No SIM / eSIM",
            "No SIM or eSIM",
            "No SIM or eSIM selected",
            "No Sent Mail",
            "No Service",
            "No W1.28 published website is available for this address.",
            "No Wi-Fi networks in range",
            "No World",
            "No active SIM or eSIM. Connect to Wi-Fi or install a subscriber profile before using cellular service.",
            "No cellular antenna in usable radio range",
            "No cellular service",
            "No linked site",
            "No local radio access. There is no usable Wi-Fi AP or authorized cellular service in range.",
            "No networks in range",
            "No other players online",
            "No physical SIM",
            "No player session",
            "No usable local phone interface. Enable Wi-Fi or Cellular Data.",
            "None",
            "Normal",
            "Not Connected",
            "Not Found",
            "Not provisioned",
            "Not provisioned - ground-terminal SATCOM backhaul only",
            "Notes",
            "Notification History",
            "Notifications",
            "Now",
            "Number",
            "Number: ",
            "O",
            "OFF",
            "OPEN",
            "Off",
            "On",
            "On/Off Labels",
            "Open",
            "Open Fitness",
            "Open Settings > Privacy & Security and allow Local Network for VS:IA Web.",
            "Open Wi-Fi Settings",
            "Open in New Tab",
            "Opened New Tab",
            "Other players can open the same domain on their phone.",
            "Overworld",
            "Overworld Signal",
            "PACKET DATA",
            "PCI / Cell",
            "PDU",
            "PDU Session",
            "PHYSICAL",
            "PHYSICAL AND MOTOR",
            "PHYSICAL SIM",
            "PLMN",
            "PLMN ",
            "POOR",
            "Partly Cloudy",
            "Password",
            "Password is checked by the server AP",
            "Password required for ",
            "Pause",
            "Paused",
            "Personalize the phone for vision, mobility, hearing, speech, and cognition.",
            "Phone URL: ",
            "Phone web test failed: ",
            "PhoneOS ",
            "PhoneOS %s is available.",
            "PhoneOS Version",
            "PhoneOS is up to date.",
            "Photo",
            "Photo unavailable",
            "Photos",
            "Physical SIM installed",
            "PhysicalCellId",
            "PhysicalIccid",
            "Play",
            "Player",
            "Player at ",
            "Please wait...",
            "Plmn",
            "Podcasts",
            "Position and world state refresh while News is open.",
            "Prefer Horizontal Text",
            "Prepare for New iPhone",
            "Preview Alert",
            "Privacy & Security",
            "ProfileType",
            "Profiles",
            "Protected",
            "Protected Network",
            "RACH / RRC / NAS registration",
            "RAN",
            "REFRESH",
            "REGISTERED",
            "REGISTERING",
            "RF DIAGNOSTICS",
            "RINGTONE AND ALERTS",
            "RRC",
            "RRC State",
            "RSRP",
            "RSRQ",
            "RSSI",
            "Rack",
            "Radio",
            "Radio is on",
            "Rain",
            "Read & Speak",
            "Ready",
            "Rear",
            "Recents",
            "Reduce Transparency",
            "Region",
            "Region changes date formatting, time zone and default units. Temperature changes the Weather widget immediately.",
            "Registered, but radio quality is insufficient for packet data",
            "Reminders",
            "Remove Bookmark",
            "Remove Current",
            "Repeat",
            "Requesting IPv4 lease",
            "Reset",
            "Reset All Settings",
            "Reset All Settings?",
            "Reset Home Screen",
            "Reset Home Screen Layout",
            "Reset Home Screen Layout?",
            "Reset Network Settings",
            "Reset Network Settings?",
            "Restores the Home Screen wallpaper and Search visibility defaults.",
            "Restricted",
            "Return to Base",
            "Returns simulated phone settings to defaults without deleting server-side messages or SIM service.",
            "Right-click to insert into your Temporary iPhone",
            "Roamed to stronger BSSID",
            "Router",
            "SA",
            "SCANNING",
            "SEARCH",
            "SEND",
            "SIMs",
            "SINR",
            "SMS service available",
            "SOS",
            "SSID",
            "STOPWATCH",
            "STORED",
            "Safari cannot open the page",
            "Satellite NTN",
            "Satellite does not replace the local phone radio unless a direct-to-device NTN service is explicitly provisioned.",
            "Save",
            "Save a page from the share menu.",
            "Save this page",
            "Saved\nTabs",
            "Scanning for nearby access points",
            "Screen Time",
            "Search",
            "Search Off",
            "Search On",
            "Search or enter website",
            "Search or enter website name",
            "Searching / synchronizing SSB",
            "Searching for cellular service",
            "Security",
            "Send",
            "Send SMS",
            "Sent",
            "Serial Number",
            "Server",
            "Server Not Found",
            "Server Tour",
            "Settings",
            "Shared with You",
            "Ships, Physics & Systems",
            "Show All",
            "Show Password",
            "Show Previews",
            "Show on Home Screen",
            "Signal",
            "Signal is too weak to associate",
            "Signality",
            "Signals & Networks",
            "Signals nominal",
            "Silent",
            "Siri",
            "Site Distance",
            "Software Update",
            "Sounds",
            "Sounds & Haptics",
            "Start",
            "Start Page",
            "Start Workout",
            "State",
            "Status",
            "Steps",
            "Stop",
            "Subnet Mask",
            "Subscriber",
            "Subscriber profile disabled",
            "Systems Lab",
            "TV",
            "Tab Closed",
            "Tabs",
            "Take a photo with Camera",
            "Tap + to start a conversation",
            "Tap Check for Update.",
            "Tap to Apply",
            "Tap to Open",
            "Tap to select / remove",
            "Tap to select profile",
            "Tap to switch",
            "Temperature",
            "Temporary iPhone",
            "Test Purchase",
            "Text Message",
            "Text Size",
            "Text Tone",
            "The SIM/eSIM remains registered for SMS service, but Cellular Data is disabled.",
            "The direct address is missing the website hostname.",
            "The eSIM profile is downloaded over Wi-Fi from the VSIA SM-DP+ server.",
            "The generated test domain is owned by another player.",
            "The generated web project is owned by another player.",
            "The phone has no usable ",
            "The simulated phone follows the selected region's time zone.",
            "These options control the VS:IA phone interface accessibility state.",
            "This updates the simulated VS:IA PhoneOS state; it does not replace your Minecraft mod files.",
            "Thunderstorm",
            "Time",
            "Time Zone",
            "Time spent with the VS:IA phone UI open.",
            "Timestamp",
            "Title",
            "To",
            "To ",
            "Today",
            "Touch",
            "Transfer or Reset",
            "Transfer or Reset iPhone",
            "Turn Wi-Fi on first",
            "Type note...",
            "Type reminder...",
            "UMTS",
            "UNKNOWN",
            "UNUSABLE",
            "UPF",
            "USIM authentication failed",
            "Unable to Check for Update",
            "Unknown",
            "Unknown Carrier",
            "Unknown local phone transport",
            "Unmute",
            "Unprovisioned physical USIM",
            "Up Next",
            "Update downloaded and ready to install.",
            "Use:\n",
            "V",
            "VERY POOR",
            "VISION",
            "VS:IA Audio",
            "VS:IA Engineering",
            "VS:IA Live",
            "VS:IA Maps",
            "VS:IA News",
            "VS:IA Podcasts",
            "VS:IA Wallet",
            "VS:IA does not yet have a cloud backup service. Your server-side SIM and SMS data are not copied by this screen.",
            "VS:IA iPhone",
            "VS:IA phone website test READY",
            "VSIA",
            "VSIA Chime",
            "VSIA Mobile",
            "VSIA Mobile SIM",
            "VSIA Mobile eSIM",
            "VSIA Phone",
            "VSIA-A26",
            "Validating default gateway",
            "Video",
            "VoiceOver",
            "Volume",
            "WEATHER",
            "WI-FI",
            "WIFI",
            "WORLD",
            "WORLD CLOCK",
            "Waiting for cellular scan",
            "Waiting for server RF scan",
            "Wallet",
            "Wallet & Apple Pay",
            "Wallpaper",
            "Weak signal - link recovery",
            "Weather",
            "Weather updates directly from the active client world.",
            "Website address",
            "What's new in Display & Text Size...",
            "Wi-Fi",
            "Wi-Fi %s | RSSI %d dBm | SINR %.1f dB | %.0f m",
            "Wi-Fi Network",
            "Wi-Fi Password",
            "Wi-Fi and Cellular are range-, obstruction-, interference-, and signal-quality dependent. ",
            "Wi-Fi is enabled but not associated. Open Wi-Fi settings and choose an in-range access point, or use cellular coverage.",
            "Wi-Fi is not associated with an access point",
            "Wi-Fi is off",
            "Wi-Fi is turned off",
            "Wi-Fi link is below usable threshold: RSSI %d dBm, SINR %.1f dB",
            "Wi-Fi password",
            "Wi-Fi signal lost",
            "WifiMac",
            "Wireless Access Unavailable",
            "Workout Active",
            "Workout tracking",
            "World Weather",
            "World status briefings",
            "Y!",
            "Yahoo",
            "Your SIM/eSIM is installed, but there is no usable cellular packet-data service at this location.",
            "Your iPhone has no usable radio access.",
            "Zoom",
            "[VSIA PHONE] No physical SIM card is in your inventory.",
            "[VSIA PHONE] Test physical SIM provisioned: ",
            "[VSIA PHONE] eSIM activation code rejected.",
            "[VSIA PHONE] eSIM download needs working Wi-Fi: ",
            "[VSIA PHONE] eSIM downloaded from VSIA SM-DP+: ",
            "[VSIA SMS] Insert or activate a SIM first.",
            "[VSIA SMS] No cellular service.",
            "[VSIA SMS] Number not found: ",
            "\\s+",
            "a",
            "alt",
            "apPassphrase",
            "article",
            "a{color:#007aff;font-weight:bold;}",
            "b",
            "background",
            "background-color",
            "black",
            "blue",
            "body",
            "body{background:#f2f2f7;color:#1c1c1e;padding:10px;}",
            "br",
            "button",
            "cellular",
            "center",
            "class",
            "color",
            "css",
            "data-href",
            "div",
            "domain.com@10.0.1.20\n",
            "eSIM",
            "eSIM is bound to another EID",
            "end",
            "font-size",
            "footer",
            "gNB ID",
            "gray",
            "green",
            "grey",
            "h ",
            "h1",
            "h2",
            "h3",
            "header",
            "hr",
            "href",
            "html",
            "iPhone Language",
            "id",
            "img",
            "internet",
            "li",
            "m",
            "main",
            "minecraft",
            "nether",
            "none",
            "open",
            "or\n",
            "orange",
            "p",
            "phone-",
            "pink",
            "pre",
            "purple",
            "px",
            "rackIp",
            "red",
            "rel",
            "rem",
            "rgb",
            "rgb\\s*\\(\\s*(\\d+)\\s*,\\s*(\\d+)\\s*,\\s*(\\d+)\\s*\\)",
            "right",
            "s",
            "section",
            "small",
            "strong",
            "style",
            "stylesheet",
            "text-align",
            "transparent",
            "tv",
            "u0000",
            "uniform",
            "vsia",
            "vsia-phone-",
            "vsia-phone-webtest",
            "white",
            "wifi",
            "wifiMac",
            "x",
            "yellow",
            "‹ CH",
            "‹ Photos"
            );

    private PhoneSystemStringCatalog() {
    }

    public static boolean contains(String text) {
        return text != null && STRINGS.contains(text);
    }

    public static Set<String> all() {
        return STRINGS;
    }

    public static int size() {
        return STRINGS.size();
    }
}
