package com.k1ngtle.vsia.phone.client;

import java.util.List;

public final class PhoneLanguageCatalog {
    public record LanguageProfile(
            String languageTag,
            String englishName,
            String nativeName,
            String defaultRegionCode
    ) {
        public String displayName() {
            if (nativeName == null
                    || nativeName.isBlank()
                    || nativeName.equalsIgnoreCase(englishName)) {
                return englishName;
            }

            return nativeName + " — " + englishName;
        }
    }

    private static final List<LanguageProfile> LANGUAGES =
            List.of(
            new LanguageProfile("en", "English", "English", "BB"),
            new LanguageProfile("fr", "French", "français", "PM"),
            new LanguageProfile("ar", "Arabic", "العربية", "EH"),
            new LanguageProfile("es", "Spanish", "español", "AR"),
            new LanguageProfile("pt", "Portuguese", "português", "GW"),
            new LanguageProfile("de", "German", "Deutsch", "LI"),
            new LanguageProfile("nl", "Dutch", "Nederlands", "NL"),
            new LanguageProfile("ru", "Russian", "русский", "RU"),
            new LanguageProfile("it", "Italian", "italiano", "IT"),
            new LanguageProfile("sw", "Swahili", "Kiswahili", "TZ"),
            new LanguageProfile("hr", "Croatian", "hrvatski", "HR"),
            new LanguageProfile("sr-Latn", "Serbian (Latin)", "srpski (latinica)", "ME"),
            new LanguageProfile("vec", "Venetian", "veneto", "SI"),
            new LanguageProfile("zh-Hant", "Chinese (Traditional)", "中文 (繁體)", "MO"),
            new LanguageProfile("hu", "Hungarian", "magyar", "HU"),
            new LanguageProfile("ro", "Romanian", "română", "RO"),
            new LanguageProfile("ta", "Tamil", "தமிழ்", "LK"),
            new LanguageProfile("sq", "Albanian", "shqip", "AL"),
            new LanguageProfile("ko", "Korean", "한국어", "KR"),
            new LanguageProfile("sr", "Serbian", "српски", "RS"),
            new LanguageProfile("sv", "Swedish", "svenska", "AX"),
            new LanguageProfile("ms", "Malay", "Melayu", "BN"),
            new LanguageProfile("qu", "Quechua", "Runasimi", "BO"),
            new LanguageProfile("tr", "Turkish", "Türkçe", "TR"),
            new LanguageProfile("el", "Greek", "Ελληνικά", "GR"),
            new LanguageProfile("fa", "Persian", "فارسی", "IR"),
            new LanguageProfile("zh", "Chinese", "中文", "CN"),
            new LanguageProfile("uk", "Ukrainian", "українська", "UA"),
            new LanguageProfile("ur", "Urdu", "اردو", "PK"),
            new LanguageProfile("bn", "Bangla", "বাংলা", "BD"),
            new LanguageProfile("fi", "Finnish", "suomi", "FI"),
            new LanguageProfile("sk", "Slovak", "slovenčina", "SK"),
            new LanguageProfile("sl", "Slovenian", "slovenščina", "SI"),
            new LanguageProfile("tn", "Tswana", "Setswana", "BW"),
            new LanguageProfile("ca", "Catalan", "català", "AD"),
            new LanguageProfile("sm", "sm", "sm", "WS"),
            new LanguageProfile("lt", "Lithuanian", "lietuvių", "LT"),
            new LanguageProfile("tk", "Turkmen", "türkmen dili", "TM"),
            new LanguageProfile("ss", "Swati", "siSwati", "SZ"),
            new LanguageProfile("ne", "Nepali", "नेपाली", "NP"),
            new LanguageProfile("nb", "Norwegian Bokmål", "norsk bokmål", "NO"),
            new LanguageProfile("st", "Southern Sotho", "Sesotho", "LS"),
            new LanguageProfile("kl", "Kalaallisut", "kalaallisut", "GL"),
            new LanguageProfile("ga", "Irish", "Gaeilge", "IE"),
            new LanguageProfile("az-Cyrl", "Azerbaijani (Cyrillic)", "азәрбајҹан (Кирил)", "AZ"),
            new LanguageProfile("ff", "Fula", "Pulaar", "SN"),
            new LanguageProfile("pl", "Polish", "polski", "PL"),
            new LanguageProfile("hy", "Armenian", "հայերեն", "AM"),
            new LanguageProfile("ml", "Malayalam", "മലയാളം", "IN"),
            new LanguageProfile("so", "Somali", "Soomaali", "SO"),
            new LanguageProfile("bg", "Bulgarian", "български", "BG"),
            new LanguageProfile("hi", "Hindi", "हिन्दी", "IN"),
            new LanguageProfile("zu", "Zulu", "isiZulu", "ZA"),
            new LanguageProfile("pa", "Punjabi", "ਪੰਜਾਬੀ", "IN"),
            new LanguageProfile("da", "Danish", "dansk", "DK"),
            new LanguageProfile("vi", "Vietnamese", "Tiếng Việt", "VN"),
            new LanguageProfile("ny", "Nyanja", "Nyanja", "MW"),
            new LanguageProfile("fil", "Filipino", "Filipino", "PH"),
            new LanguageProfile("ps", "Pashto", "پښتو", "AF"),
            new LanguageProfile("gu", "Gujarati", "ગુજરાતી", "IN"),
            new LanguageProfile("ln", "Lingala", "lingála", "CD"),
            new LanguageProfile("pap", "Papiamento", "Papiamentu", "AW"),
            new LanguageProfile("be", "Belarusian", "беларуская", "BY"),
            new LanguageProfile("ja", "Japanese", "日本語", "JP"),
            new LanguageProfile("uz", "Uzbek", "o‘zbek", "UZ"),
            new LanguageProfile("ms-Arab", "Malay (Arabic)", "بهاس ملايو (عرب)", "BN"),
            new LanguageProfile("az", "Azerbaijani", "azərbaycan", "AZ"),
            new LanguageProfile("af", "Afrikaans", "Afrikaans", "ZA"),
            new LanguageProfile("ka", "Georgian", "ქართული", "GE"),
            new LanguageProfile("gn", "Guarani", "avañe’ẽ", "PY"),
            new LanguageProfile("rw", "Kinyarwanda", "Ikinyarwanda", "RW"),
            new LanguageProfile("mk", "Macedonian", "македонски", "MK"),
            new LanguageProfile("az-Arab", "Azerbaijani (Arabic)", "آذربایجان تۆرکجه‌سی (عربجه)", "IQ"),
            new LanguageProfile("ts", "Tsonga", "Xitsonga", "ZA"),
            new LanguageProfile("se", "Northern Sami", "davvisámegiella", "NO"),
            new LanguageProfile("bo", "Tibetan", "བོད་སྐད་", "CN"),
            new LanguageProfile("no", "Norwegian", "norsk", "NO"),
            new LanguageProfile("cs", "Czech", "čeština", "CZ"),
            new LanguageProfile("dv", "Divehi", "ދިވެހިބަސް", "MV"),
            new LanguageProfile("fo", "Faroese", "føroyskt", "FO"),
            new LanguageProfile("mn", "Mongolian", "монгол", "MN"),
            new LanguageProfile("et", "Estonian", "eesti", "EE"),
            new LanguageProfile("id", "Indonesian", "Indonesia", "ID"),
            new LanguageProfile("my", "Burmese", "မြန်မာ", "MM"),
            new LanguageProfile("kk", "Kazakh", "қазақ тілі", "KZ"),
            new LanguageProfile("dz", "Dzongkha", "རྫོང་ཁ", "BT"),
            new LanguageProfile("ch", "ch", "ch", "GU"),
            new LanguageProfile("am", "Amharic", "አማርኛ", "ET"),
            new LanguageProfile("ee", "Ewe", "eʋegbe", "GH"),
            new LanguageProfile("ckb", "Central Kurdish", "کوردیی ناوەندی", "IQ"),
            new LanguageProfile("ay", "ay", "ay", "BO"),
            new LanguageProfile("yo", "Yoruba", "Èdè Yorùbá", "NG"),
            new LanguageProfile("xh", "Xhosa", "IsiXhosa", "ZA"),
            new LanguageProfile("sd", "Sindhi", "سنڌي", "IN"),
            new LanguageProfile("uz-Cyrl", "Uzbek (Cyrillic)", "ўзбекча (Кирил)", "UZ"),
            new LanguageProfile("mai", "Maithili", "मैथिली", "IN"),
            new LanguageProfile("gl", "Galician", "galego", "ES"),
            new LanguageProfile("oc", "Occitan", "occitan", "ES"),
            new LanguageProfile("ve", "Venda", "Tshivenḓa", "ZA"),
            new LanguageProfile("war", "war", "war", "PH"),
            new LanguageProfile("knf", "knf", "knf", "SN"),
            new LanguageProfile("os", "Ossetic", "ирон", "GE"),
            new LanguageProfile("ab", "Abkhazian", "Аԥсшәа", "GE"),
            new LanguageProfile("eu", "Basque", "euskara", "ES"),
            new LanguageProfile("cy", "Welsh", "Cymraeg", "GB"),
            new LanguageProfile("kbd", "kbd", "kbd", "RU"),
            new LanguageProfile("ug", "Uyghur", "ئۇيغۇرچە", "CN"),
            new LanguageProfile("ks", "Kashmiri", "کٲشُر", "IN"),
            new LanguageProfile("ady", "ady", "ady", "RU"),
            new LanguageProfile("he", "Hebrew", "עברית", "IL"),
            new LanguageProfile("is", "Icelandic", "íslenska", "IS"),
            new LanguageProfile("mt", "Maltese", "Malti", "MT"),
            new LanguageProfile("tg", "Tajik", "тоҷикӣ", "TJ"),
            new LanguageProfile("bs", "Bosnian", "bosanski", "BA"),
            new LanguageProfile("bs-Cyrl", "Bosnian (Cyrillic)", "босански (ћирилица)", "BA"),
            new LanguageProfile("to", "Tongan", "lea fakatonga", "TO"),
            new LanguageProfile("mg", "Malagasy", "Malagasy", "MG"),
            new LanguageProfile("bi", "bi", "bi", "VU"),
            new LanguageProfile("km", "Khmer", "ខ្មែរ", "KH"),
            new LanguageProfile("tvl", "tvl", "tvl", "TV"),
            new LanguageProfile("ht", "Haitian Creole", "Kreyòl Ayisyen", "HT"),
            new LanguageProfile("sn", "Shona", "chiShona", "ZW"),
            new LanguageProfile("th", "Thai", "ไทย", "TH"),
            new LanguageProfile("pau", "pau", "pau", "PW"),
            new LanguageProfile("mh", "mh", "mh", "MH"),
            new LanguageProfile("tpi", "Tok Pisin", "Tok Pisin", "PG"),
            new LanguageProfile("na", "na", "na", "NR"),
            new LanguageProfile("lo", "Lao", "ລາວ", "LA"),
            new LanguageProfile("tkl", "tkl", "tkl", "TK"),
            new LanguageProfile("si", "Sinhala", "සිංහල", "LK"),
            new LanguageProfile("lb", "Luxembourgish", "Lëtzebuergesch", "LU"),
            new LanguageProfile("rn", "Rundi", "Ikirundi", "BI"),
            new LanguageProfile("lv", "Latvian", "latviešu", "LV"),
            new LanguageProfile("gil", "gil", "gil", "KI"),
            new LanguageProfile("tet", "tet", "tet", "TL"),
            new LanguageProfile("nan-Hant", "nan-Hant", "nan-Hant", "TW"),
            new LanguageProfile("niu", "niu", "niu", "NU"),
            new LanguageProfile("sg", "Sango", "Sängö", "CF"),
            new LanguageProfile("ky", "Kyrgyz", "кыргызча", "KG"),
            new LanguageProfile("hif", "hif", "hif", "FJ"),
            new LanguageProfile("fj", "fj", "fj", "FJ"),
            new LanguageProfile("ak", "Akan", "Akan", "GH"),
            new LanguageProfile("zdj", "zdj", "zdj", "KM"),
            new LanguageProfile("wni", "wni", "wni", "KM"),
            new LanguageProfile("ty", "ty", "ty", "PF"),
            new LanguageProfile("nn", "Norwegian Nynorsk", "norsk nynorsk", "NO"),
            new LanguageProfile("ceb", "Cebuano", "Cebuano", "PH"),
            new LanguageProfile("nd", "North Ndebele", "isiNdebele", "ZW"),
            new LanguageProfile("srr", "srr", "srr", "SN"),
            new LanguageProfile("hak-Hant", "hak-Hant", "hak-Hant", "TW"),
            new LanguageProfile("tzm", "Central Atlas Tamazight", "Tamaziɣt n laṭlaṣ", "MA"),
            new LanguageProfile("lua", "lua", "lua", "CD"),
            new LanguageProfile("ilo", "ilo", "ilo", "PH"),
            new LanguageProfile("nso", "Northern Sotho", "Sesotho sa Leboa", "ZA"),
            new LanguageProfile("hil", "hil", "hil", "PH"),
            new LanguageProfile("te", "Telugu", "తెలుగు", "IN"),
            new LanguageProfile("quc", "Kʼicheʼ", "Kʼicheʼ", "GT"),
            new LanguageProfile("mr", "Marathi", "मराठी", "IN"),
            new LanguageProfile("uz-Arab", "Uzbek (Arabic)", "اوزبیک (عربی)", "AF"),
            new LanguageProfile("fy", "Western Frisian", "Frysk", "NL"),
            new LanguageProfile("kn", "Kannada", "ಕನ್ನಡ", "IN"),
            new LanguageProfile("or", "Odia", "ଓଡ଼ିଆ", "IN"),
            new LanguageProfile("gaa", "Ga", "Gã", "GH"),
            new LanguageProfile("mi", "Māori", "Māori", "NZ"),
            new LanguageProfile("dyo", "Jola-Fonyi", "joola", "SN"),
            new LanguageProfile("ho", "ho", "ho", "PG"),
            new LanguageProfile("gv", "Manx", "Gaelg", "IM"),
            new LanguageProfile("nr", "South Ndebele", "isiNdebele", "ZA"),
            new LanguageProfile("kg", "kg", "kg", "CD"),
            new LanguageProfile("sav", "sav", "sav", "SN"),
            new LanguageProfile("pag", "pag", "pag", "PH"),
            new LanguageProfile("tt", "Tatar", "татар", "RU"),
            new LanguageProfile("ast", "Asturian", "asturianu", "ES"),
            new LanguageProfile("as", "Assamese", "অসমীয়া", "IN"),
            new LanguageProfile("ba", "Bashkir", "башҡорт теле", "RU"),
            new LanguageProfile("mdh", "mdh", "mdh", "PH"),
            new LanguageProfile("tsg", "tsg", "tsg", "PH"),
            new LanguageProfile("mfv", "mfv", "mfv", "SN"),
            new LanguageProfile("ce", "Chechen", "нохчийн", "RU"),
            new LanguageProfile("bjt", "bjt", "bjt", "SN"),
            new LanguageProfile("sat", "Santali", "ᱥᱟᱱᱛᱟᱲᱤ", "IN"),
            new LanguageProfile("rm", "Romansh", "rumantsch", "CH"),
            new LanguageProfile("av", "av", "av", "RU"),
            new LanguageProfile("udm", "udm", "udm", "RU"),
            new LanguageProfile("kok", "Konkani", "कोंकणी", "IN"),
            new LanguageProfile("sah", "Yakut", "саха тыла", "RU"),
            new LanguageProfile("za", "Zhuang", "Vahcuengh", "CN"),
            new LanguageProfile("myv", "Erzya", "эрзянь кель", "RU"),
            new LanguageProfile("mn-Mong", "Mongolian (Mongolian)", "None", "CN"),
            new LanguageProfile("snf", "snf", "snf", "SN"),
            new LanguageProfile("mdf", "Moksha", "мокшень кяль", "RU"),
            new LanguageProfile("kum", "kum", "kum", "RU"),
            new LanguageProfile("kv", "kv", "kv", "RU"),
            new LanguageProfile("lez", "lez", "lez", "RU"),
            new LanguageProfile("krc", "krc", "krc", "RU"),
            new LanguageProfile("inh", "inh", "inh", "RU"),
            new LanguageProfile("sd-Deva", "Sindhi (Devanagari)", "सिन्धी (देवनागिरी)", "IN"),
            new LanguageProfile("csb", "csb", "csb", "PL"),
            new LanguageProfile("tyv", "Tuvinian", "None", "RU"),
            new LanguageProfile("iu", "Inuktitut", "ᐃᓄᒃᑎᑐᑦ", "CA"),
            new LanguageProfile("iu-Latn", "Inuktitut (Latin)", "None", "CA"),
            new LanguageProfile("gd", "Scottish Gaelic", "Gàidhlig", "GB"),
            new LanguageProfile("bsc", "bsc", "bsc", "SN"),
            new LanguageProfile("kha", "kha", "kha", "IN"),
            new LanguageProfile("lbe", "lbe", "lbe", "RU"),
            new LanguageProfile("koi", "koi", "koi", "RU"),
            new LanguageProfile("mey", "mey", "mey", "SN"),
            new LanguageProfile("crk", "crk", "crk", "CA"),
            new LanguageProfile("chp", "chp", "chp", "CA"),
            new LanguageProfile("tnr", "tnr", "tnr", "SN"),
            new LanguageProfile("frr", "Northern Frisian", "Nordfriisk", "DE"),
            new LanguageProfile("sms", "Skolt Sami", "sääʹmǩiõll", "FI"),
            new LanguageProfile("haw", "Hawaiian", "ʻŌlelo Hawaiʻi", "US"),
            new LanguageProfile("den", "den", "den", "CA"),
            new LanguageProfile("dgr", "dgr", "dgr", "CA"),
            new LanguageProfile("sa", "Sanskrit", "संस्कृत भाषा", "IN"),
            new LanguageProfile("gwi", "gwi", "gwi", "CA"),
            new LanguageProfile("ff-Adlm", "Fula (Adlam)", "𞤆𞤵𞤤𞤢𞤪 (𞤀𞤁𞤂𞤢𞤃)", "BF"),
            new LanguageProfile("hnj", "Hmong Njua", "𞄀𞄄𞄰𞄩𞄍𞄜𞄰", "LA"),
            new LanguageProfile("kaa", "Kara-Kalpak", "қарақалпақша", "UZ"),
            new LanguageProfile("ku", "Kurdish", "kurdî (kurmancî)", "SY"),
            new LanguageProfile("apc", "None", "العامية", "LB"),
            new LanguageProfile("yue", "Cantonese", "粵語", "HK"),
            new LanguageProfile("gsw", "Swiss German", "Schwiizertüütsch", "LI"),
            new LanguageProfile("bal", "Baluchi", "بلۆچی", "OM"),
            new LanguageProfile("kk-Arab", "Kazakh (Arabic)", "قازاق ءتىلى (اراب جازۋى)", "MN"),
            new LanguageProfile("yi", "Yiddish", "ייִדיש", "IL"),
            new LanguageProfile("und", "English (United States)", "English (United States)", "AQ"),
            new LanguageProfile("ti", "Tigrinya", "ትግርኛ", "ER"),
            new LanguageProfile("ha", "Hausa", "Hausa", "NE"),
            new LanguageProfile("aa", "Afar", "Qafar", "DJ"),
            new LanguageProfile("om", "Oromo", "Oromoo", "ET"),
            new LanguageProfile("bho", "Bhojpuri", "भोजपुरी", "MU"),
            new LanguageProfile("lep", "lep", "lep", "BT"),
            new LanguageProfile("ha-Arab", "Hausa (Arabic)", "None", "SD"),
            new LanguageProfile("bgn", "Western Balochi", "بلوچی (رخشانی)", "AF"),
            new LanguageProfile("kdt", "kdt", "kdt", "LA"),
            new LanguageProfile("yrl", "Nheengatu", "nheẽgatu", "BR"),
            new LanguageProfile("bar", "bar", "bar", "AT"),
            new LanguageProfile("wo", "Wolof", "Wolof", "SN"),
            new LanguageProfile("man", "man", "man", "GM"),
            new LanguageProfile("man-Nkoo", "man-Nkoo", "man-Nkoo", "GM"),
            new LanguageProfile("lah", "lah", "lah", "PK"),
            new LanguageProfile("jv", "Javanese", "Jawa", "ID"),
            new LanguageProfile("men", "men", "men", "SL"),
            new LanguageProfile("nds", "Low German", "Neddersass’sch", "DE"),
            new LanguageProfile("kpe", "Kpelle", "Kpɛlɛɛ", "LR"),
            new LanguageProfile("ndc", "ndc", "ndc", "MZ"),
            new LanguageProfile("tum", "tum", "tum", "MW")
            );

    private PhoneLanguageCatalog() {
    }

    public static List<LanguageProfile> all() {
        return LANGUAGES;
    }

    public static LanguageProfile byTag(String tag) {
        if (tag != null) {
            for (LanguageProfile profile : LANGUAGES) {
                if (profile.languageTag()
                        .equalsIgnoreCase(tag)) {
                    return profile;
                }
            }
        }

        return LANGUAGES.get(0);
    }

    public static LanguageProfile englishUk() {
        for (LanguageProfile profile : LANGUAGES) {
            if (profile.languageTag().equalsIgnoreCase("en")) {
                return profile;
            }
        }

        return LANGUAGES.get(0);
    }

    public static int size() {
        return LANGUAGES.size();
    }
}
