package com.k1ngtle.vsia.signality.engineering.wifi.integration.w121;

public enum W121IntegrationFailure {
    NONE,
    INVALID_TOPOLOGY,
    AP_CONFIGURATION_FAILED,
    STATION_CONFIGURATION_FAILED,
    SCAN_START_FAILED,
    SCAN_TIMEOUT,
    CONNECT_START_FAILED,
    ASSOCIATION_TIMEOUT,
    SECURITY_FAILED,
    DATA_START_FAILED,
    DATA_ACK_TIMEOUT,
    RAW_WORKFLOW_START_FAILED,
    RAW_WORKFLOW_FAILED,
    RAW_WORKFLOW_TIMEOUT,
    HTTP_NOT_200,
    DISTRIBUTION_PATH_NOT_OBSERVED,
    INTERNAL_ERROR
}
