minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=vsia
mod_name=VSIA
mod_license=All Rights Reserved
mod_version=1.0.0
mod_authors=k1ngtle
mod_description=Tactical equipment and radar integrations for Valkyrien Skies.

# Dependency Versions
vs2_version=2.3.0-beta.5
geckolib_version=4.4.7
vpb_version=1.11.1

vs2_version_range=[2.3.0-beta.5,2.5.0)

vs2_compile_artifact=2.3.0-beta.5tt22x2

vs2_runtime_artifact=2.3.0-beta.5tt22x2
