package com.k1ngtle.vsia.signality.engineering.wifi.integration.w124;

public enum W124QosFailure {
    NONE,
    INVALID_TOPOLOGY,
    AP_CONFIGURATION_FAILED,
    STATION_CONFIGURATION_FAILED,
    SCAN_START_FAILED,
    SCAN_TIMEOUT,
    CONNECT_START_FAILED,
    ASSOCIATION_TIMEOUT,
    SECURITY_FAILED,
    CATEGORY_QUEUE_REJECTED,
    CATEGORY_NOT_VISIBLE_AT_MAC,
    CATEGORY_DRAIN_TIMEOUT,
    CATEGORY_DELIVERY_FAILED,
    MIXED_LOAD_REJECTED,
    MIXED_LOAD_DRAIN_TIMEOUT,
    MIXED_LOAD_DELIVERY_FAILED,
    INTERNAL_ERROR
}
