package com.k1ngtle.vsia.signality.engineering.wifi.integration.w126;

public enum W126Failure {
    NONE,
    INVALID_TOPOLOGY,
    PROFILE_CONFIGURATION_FAILED,
    AP_CONFIGURATION_FAILED,
    STATION_CONFIGURATION_FAILED,
    SCAN_START_FAILED,
    SCAN_TIMEOUT,
    CONNECT_START_FAILED,
    ASSOCIATION_TIMEOUT,
    SECURITY_FAILED,
    LINK_ACK_TIMEOUT,
    SERVICE_START_FAILED,
    SERVICE_FAILED,
    DUPLICATE_IPV4,
    PROVIDER_DOMAIN_MISMATCH,
    QOS_QUEUE_FAILED,
    QOS_DELIVERY_FAILED,
    ROAM_POLICY_NOT_MET,
    ROAM_TIMEOUT,
    IPV4_CHANGED_DURING_MOBILITY,
    POST_MOBILITY_SERVICE_FAILED,
    SCALE_STABILITY_FAILED,
    DISTRIBUTION_PATH_NOT_OBSERVED,
    INTERNAL_ERROR
}
