package com.k1ngtle.vsia.signality.engineering.wifi.integration.w123;

public enum W123ClosureFailure {
    NONE,
    INVALID_TOPOLOGY,
    AP_CONFIGURATION_FAILED,
    STATION_CONFIGURATION_FAILED,
    SCAN_START_FAILED,
    SCAN_TIMEOUT,
    CONNECT_START_FAILED,
    ASSOCIATION_TIMEOUT,
    SECURITY_FAILED,
    MODERATE_BURST_REJECTED,
    MODERATE_DRAIN_TIMEOUT,
    MODERATE_METRICS_INVALID,
    SATURATION_BURST_REJECTED,
    QUEUE_CAPACITY_INVALID,
    QUEUE_OVERFLOW_NOT_OBSERVED,
    SATURATION_DRAIN_TIMEOUT,
    SATURATION_METRICS_INVALID,
    RF_PROBE_INVALID,
    INTERNAL_ERROR
}
