package com.k1ngtle.vsia.signality.engineering.cellular;
public enum CellularMessageType {
    SSB, RACH_PREAMBLE, RANDOM_ACCESS_RESPONSE, RRC_SETUP_REQUEST,
    RRC_SETUP, REGISTRATION_REQUEST, REGISTRATION_ACCEPT,
    MEASUREMENT_REPORT, HANDOVER_COMMAND, HANDOVER_COMPLETE, DATA
}
