package com.k1ngtle.vsia.signality.engineering.wifi.integration.w127;

public enum W127Failure {
    NONE,
    INVALID_TOPOLOGY,
    BOOTSTRAP_FAILED,
    BASELINE_AXFR_FAILED,
    BASELINE_DNS_FAILED,
    ROOT_RETRY_FAILED,
    ROOT_OUTAGE_NOT_DETECTED,
    ROOT_RECOVERY_FAILED,
    TLD_OUTAGE_NOT_DETECTED,
    TLD_RECOVERY_FAILED,
    SECONDARY_FAILOVER_FAILED,
    DNSSEC_TAMPER_ACCEPTED,
    DNSSEC_EXPIRED_ACCEPTED,
    DNSSEC_DS_MISMATCH_ACCEPTED,
    DNSSEC_RRSIG_ACCEPTED,
    SERVFAIL_ACCEPTED,
    DUPLICATE_NOT_IDEMPOTENT,
    AXFR_REORDER_FAILED,
    AXFR_PARTIAL_COMMIT,
    AXFR_RETRY_FAILED,
    IXFR_STALE_FALLBACK_FAILED,
    FINAL_BASELINE_FAILED,
    FAULT_CLEANUP_FAILED,
    TIMEOUT,
    INTERNAL_ERROR
}
