package com.k1ngtle.vsia.signality.engineering.wifi.integration.w127;

public enum W127Stage {
    SETUP,
    BASELINE_AXFR,
    BASELINE_DNS,
    ROOT_SINGLE_DROP_RECOVERY,
    ROOT_OUTAGE_EXPECTED_FAIL,
    ROOT_POST_OUTAGE_RECOVERY,
    TLD_OUTAGE_EXPECTED_FAIL,
    TLD_POST_OUTAGE_RECOVERY,
    PRIMARY_OUTAGE_SECONDARY_FAILOVER,
    ROOT_RRSIG_TAMPER_REJECT,
    TLD_EXPIRED_SIGNATURE_REJECT,
    AUTH_DNSKEY_DS_MISMATCH_REJECT,
    AUTH_RRSIG_TAMPER_REJECT,
    DUPLICATE_REFERRAL_IDEMPOTENCE,
    SERVFAIL_REJECT,
    AXFR_REORDER_TOLERANCE,
    AXFR_DROP_INCOMPLETE_SAFE,
    AXFR_RETRY_RECOVERY,
    IXFR_STALE_SERIAL_FALLBACK,
    FINAL_BASELINE,
    CLEAN_STABILITY,
    COMPLETE,
    FAILED
}
