package com.k1ngtle.vsia.signality.engineering.cellular.nas;

public enum NasMessageType {
    REGISTRATION_REQUEST,
    AUTHENTICATION_REQUEST,
    AUTHENTICATION_RESPONSE,
    SECURITY_MODE_COMMAND,
    SECURITY_MODE_COMPLETE,
    REGISTRATION_ACCEPT,
    PDU_SESSION_ESTABLISHMENT_REQUEST,
    PDU_SESSION_ESTABLISHMENT_ACCEPT
}
